version: '3.9'

services:
  postgres:
    container_name: coding-playground-postgres
    image: postgres
    environment:
      - POSTGRES_USER=playground
      - POSTGRES_DB=playground
      - POSTGRES_PASSWORD=playground
    volumes:
      - dev-postgres-data:/var/lib/postressql/data 
    ports:
      - "5431:5432"
  
volumes:
  dev-postgres-data:
